#festival-promoters-tickets-31 Decrease tickets page load time (#33)
* #festival-promoters-tickets-31 Decrease tickets page load time

Added spinner to tickets page
Changed DTO for ticket item for display list of tickets

Fixes #31

* version up

* Disabled frontend tests - too slow

* #festival-promoters-tickets-31 Decrease tickets page load time

Added spinner to tickets page
Changed DTO for ticket item for display list of tickets

Fixes #31

* version up

* Disabled frontend tests - too slow

* WIP:
```
main.5324bee35b9f36c68116.bundle.js:2 ERROR DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://organic-promo-tickets.herokuapp.com/api/tickets/1301'.
    at XMLHttpRequest.__zone_symbol__send (<anonymous>:1:774)
    at https://organic-promo-tickets.herokuapp.com/app/main.5324bee35b9f36c68116.bundle.js:2:1275364
    at XMLHttpRequest.E.s.<computed> [as send] (https://organic-promo-tickets.herokuapp.com/app/main.5324bee35b9f36c68116.bundle.js:2:1252333)
    at Object.i [as default] (https://organic-promo-tickets.herokuapp.com/app/0.5324bee35b9f36c68116.chunk.js:1:10033)
    at e.get (https://organic-promo-tickets.herokuapp.com/app/0.5324bee35b9f36c68116.chunk.js:1:7950)
    at e.get (https://organic-promo-tickets.herokuapp.com/app/0.5324bee35b9f36c68116.chunk.js:1:7347)
    at l.findSync (https://organic-promo-tickets.herokuapp.com/app/0.5324bee35b9f36c68116.chunk.js:1:3056)
    at R.getTicket (https://organic-promo-tickets.herokuapp.com/app/1.5324bee35b9f36c68116.chunk.js:1:16016)
    at R.downloadFile (https://organic-promo-tickets.herokuapp.com/app/1.5324bee35b9f36c68116.chunk.js:1:17308)
    at https://organic-promo-tickets.herokuapp.com/app/1.5324bee35b9f36c68116.chunk.js:1:11758

```

* WIP:
```
main.5324bee35b9f36c68116.bundle.js:2 ERROR DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://organic-promo-tickets.herokuapp.com/api/tickets/1301'.
    at XMLHttpRequest.__zone_symbol__send (<anonymous>:1:774)
    at https://organic-promo-tickets.herokuapp.com/app/main.5324bee35b9f36c68116.bundle.js:2:1275364
    at XMLHttpRequest.E.s.<computed> [as send] (https://organic-promo-tickets.herokuapp.com/app/main.5324bee35b9f36c68116.bundle.js:2:1252333)
    at Object.i [as default] (https://organic-promo-tickets.herokuapp.com/app/0.5324bee35b9f36c68116.chunk.js:1:10033)
    at e.get (https://organic-promo-tickets.herokuapp.com/app/0.5324bee35b9f36c68116.chunk.js:1:7950)
    at e.get (https://organic-promo-tickets.herokuapp.com/app/0.5324bee35b9f36c68116.chunk.js:1:7347)
    at l.findSync (https://organic-promo-tickets.herokuapp.com/app/0.5324bee35b9f36c68116.chunk.js:1:3056)
    at R.getTicket (https://organic-promo-tickets.herokuapp.com/app/1.5324bee35b9f36c68116.chunk.js:1:16016)
    at R.downloadFile (https://organic-promo-tickets.herokuapp.com/app/1.5324bee35b9f36c68116.chunk.js:1:17308)
    at https://organic-promo-tickets.herokuapp.com/app/1.5324bee35b9f36c68116.chunk.js:1:11758

```

* Paginate tickets page
Added missing commit code regarding sync getting ticket dto
WIP: fixinf download file from ticket details

* Added badge to enabled column in ticket table
Descending order of tickets id on ticket table